config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "friends#index"
  resources :friends, only: [:index, :show, :new, :create, :update] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :index, :destroy]
  get "pages/:id", to: "pages#show", as: :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :friend
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
    has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model

  pg_search_scope :global_search,
  against: [ :hobbies, :zodiac_sign],
  associated_against: {
    user: [:first_name, :last_name, :gender, :age, :nationality]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_one :friend
  has_many :bookings
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :age, :address, :birth_date, :nationality, :gender, :phone, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :age, :address, :birth_date, :nationality, :gender, :phone])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @friend = Friend.find(params[:friend_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @friend = Friend.find(params[:friend_id])
    @booking.friend = @friend
    if @booking.save
      redirect_to profile_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to profile_path(current_user), status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:occurs_on, :friend_id)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController




  def index
    if params[:query].present?
      @friends = Friend.global_search(params[:query])
    else
      @friends = Friend.all
    end
    # The `geocoded` scope filters only flats with coordinates
    #  @markers = @friends.geocoded.map do |friend|
       # {
        #  lat: friend.latitude,
       #   lng: friend.longitude
      #  }
     # end
  end

  def show
    @friend = Friend.find(params[:id])
    @user = User.find(@friend.user_id)
    @booking = Booking.new
  end

  def new
    if !current_user.friend.nil?
      @friend = current_user.friend

    else
      @friend = Friend.new
    end
  end

  def create
    @friend = Friend.new(friend_params)
    @friend.user = current_user
    if @friend.save
      redirect_to friend_path(@friend)
    else
      render :new
    end
  end

  def update
    @friend = current_user.friends.last
    if @friend.update(friend_params)
      redirect_to profile_path(current_user)
    else
      render :new
    end
  end

  private

  def friend_params
    params.require(:friend).permit(:hobbies, :price, :zodiac_sign, :pronouns, :about_me, :availability)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  def show
    @user = User.find(params[:id])
    @bookings = Booking.where(user: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @friends = Friends.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<div class="container-new-friend">
  <h2> Here you can book me as a Friend  </h2>
  <div class="new-friend p-3 shadow" >
    <%= simple_form_for [@friend, @booking] do |f| %>
      <div class="date">
        <%= f.input :occurs_on %>
      </div>
    <div class="buttonss">
      <%= f.submit "Book me now!", class: "btn btn-success" %>
      <%= link_to 'Cancel me now!', friend_path(@friend), class: "btn btn-danger"%>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/friends/index.html.erb
<div class="home-container">
  <div class="search-bar">
  <%= form_with url: friends_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a friend"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
  </div>

  <div class="map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>



  <div class="cards">
    <% @friends.each do |friend| %>
      <%  if current_user && friend.user_id == current_user.id %>
        <% next %>
      <% else %>
        <%= link_to friend_path(friend), class: "card-profile" do %>
          <% if friend.user.photo.key %>
            <img class="card-profile-image" src="<%= cl_image_path friend.user.photo.key %>" alt="">

            <div class="card-profile-overview">
                <div class="card-profile-info">
                  <h2><%= friend.user.first_name %></h2>
                  <p><%=  friend.hobbies.capitalize%></p>
                </div>
                <h2 class="card-profile-price"> <%= friend.price %> € </h2>
            </div>
          <% else %>
            <div class="card-profile-image" style="background-image:  url(https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGVyc29ufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60)">
            </div>
            <div class="card-profile-overview">
                <div class="card-profile-info">
                  <h2><%= friend.user.first_name %></h2>
                  <p><%=  friend.hobbies.capitalize%></p>
                </div>
                <h2 class="card-profile-price"> <%= friend.price %> € </h2>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>


<!-- >
 <div class="home-friend-card">
    <% @friends.each do |friend| %>
      <%  if current_user && friend.user_id == current_user.id %>
        <% next %>
      <% else %>
        <%= link_to friend_path(friend), class: "card-trip" do %>
          <% if friend.user.photo.key %>
            <div class="card-trip-infos" style="background-image: url('<%= cl_image_path friend.user.photo.key, backgroundsize: :cover, crop: :fill %>')">
              <div>
                <h2><%= friend.user.first_name %></h2>
                <p><%=  friend.hobbies.capitalize%></p>
              </div>
              <h2 class="card-trip-pricing"> <%= friend.price %> €</h2>
            </div>
            <% else %>
                        <div class="card-trip-infos" style="background-image: url(https://images.unsplash.com/photo-1669187737670-921c6137a033?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDF8Q0R3dXdYSkFiRXd8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60)">
              <div>
                <h2><%= friend.user.first_name %></h2>
                <p><%=  friend.hobbies.capitalize%></p>
              </div>
              <h2 class="card-trip-pricing"> <%= friend.price %> €</h2>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>

app/views/friends/new.html.erb
<div class="container-new-friend">
  <div class="new-friend">
    <h1>Register as a <strong>friend</strong> :</h1>
    <div class="about-me">
      <%= simple_form_for(@friend) do |f| %>
      <%= f.input :about_me %>
      <%= f.input :hobbies %>
      <%= f.input :price %>
      <%= f.input :zodiac_sign %>
      <%= f.input :availability %>
      <%= f.input :pronouns %>
        <div class="buttons1">
          <%= f.submit "Submit", class: "btn btn-success" %>
          <%= link_to 'Back to home page', friends_path(@friend), class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/friends/show.html.erb
<div class="friend-container">
  <% if @friend.user.photo.key %>
    <div class="friend-image" style="background-image: url('<%= cl_image_path @user.photo.key, backgroundsize: :cover, crop: :fill %>')" >
  <% else %>
    <div class="friend-image" style="background-image: url('https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGVyc29ufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60')" >
  <% end %>
      <h1><%= @friend.user.first_name %> <%= @friend.user.last_name %></h1>
      <%= link_to "Book #{@friend.user.first_name} for #{@friend.price}€ a day", new_friend_booking_path(@friend), class:"btn btn-secondary"%>
    </div>

  <div class="friend-info">

    <div class="friend-details">
      <div class="About">
        <h5>About Me:</h5>
        <p><%= @friend.about_me %></p>
      </div>

      <div class="Zodiac">
        <h5>My Zodiac Sign:</h5>
        <p><%= @friend.zodiac_sign %></p>
      </div>

      <div class="Hobbies">
        <h5>My Hobbies:</h5>
        <p><%= @friend.hobbies %></p>
      </div>

      <div class="Pronouns">
        <h5>My Pronouns:</h5>
        <p><%= @friend.pronouns %></p>
      </div>
    </div>

    <div class="price-availability">
      <div class="Availability">
          <h5>My Availability:</h5>
          <p><%= @friend.availability %></p>
        </div>
    </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAFriend</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/show.html.erb
<div class="profile-container">
  <div>
    <% if @user.photo.key %>
      <div class="friend-image" style="background-image: url('<%= cl_image_path @user.photo.key, backgroundsize: :cover, crop: :fill %>')" >
    <% else %>
      <div class="friend-image" style="background-image: url('https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGVyc29ufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60')" >
    <% end %>
      <h1><%=  @user.first_name %> <%= @user.last_name %></h1>
      <%= link_to link_to 'Sign up to become a friend', new_friend_path(@friend), class:"btn btn-secondary"%>
  </div>

  <div class="profile-info">

    <div class="profile-details">
      <div class="Email">
        <h5>My Email:</h5>
        <p><%= @user.email %></p>
      </div>

      <div class="Address">
        <h5>My Address:</h5>
        <p><%= @user.address %></p>
      </div>

      <div class="Age">
        <h5>My Age:</h5>
        <p><%= @user.age %></p>
      </div>

      <div class="Birth-date">
        <h5>My Birthdate:</h5>
        <p><%= @user.birth_date %></p>
      </div>

      <div class="Gender">
        <h5>My Gender:</h5>
        <p><%= @user.gender %></p>
      </div>
    </div>

    <div class="My-Bookings">
      <h4>My Bookings:</h4>
      <div class="Bookings">
        <% @bookings.each do |booking|%>
          <%= booking.friend.user.first_name %> - <%= booking.occurs_on %>
          <div>
          <%= link_to "Delete", booking_path(booking), class:"btn btn-secondary btn-sm", data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
          </div>
          <% end %>
      </div>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-airbnb">
  <div class="container-fluid">
    <%= link_to friends_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/2583/2583035.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="Rent-a-friend"><h4>Rent a friend</h4></div>
    <%# <div class="buttons">
      <button class="search-your-friend"><%= link_to "Search your friend", "#", class: "btn btn-ghost" %></button>

    <div class="secondpart">
      <ul class="navbar-nav me-auto">
          <li class="nav-item dropdown">
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjoXyX2SJzeszHi_uHo-S0kWJKjbVhIB4atb1g7LxIp1wdjqrP9Bz7zIHBVBnmBuJorFc&usqp=CAU", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end">
              <% if current_user %>
                  <%= link_to "My Profile", profile_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
                <% else %>
                  <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
                  <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>